#ifndef CONFIG_H
#define CONFIG_H

#define EMULATOR_WINDOW_TITLE "Chip7"
#define CHIP7_MEMORY_SIZE 4096
#define CHIP7_PROG_LOAD_ADDR 0x200


#define CHIP7_SCREEN_WIDTH 64
#define CHIP7_SCREEN_HEIGHT 32
#define CHIP7_RENDER_SCALE 10

#define CHIP7_REGISTER_TOTAL 16
#define CHIP7_STACK_TOTAL 16
#define CHIP7_KEY_TOTAL 16
#define CHIP7_CHARACTER_SET_ADDR 0x00

#define FPS 60
#define MILLISECS_PER_FRAME 1000/FPS

#define CHIP7_DEFAULT_SPRITE_HEIGHT 5

#endif
